window.WL.langData = {
  "ar": {
    "button_download": "تحميل",
    "button_sign_in": "تسجيل الدخول",
    "button_log_out": "تسجيل الخروج",
    "button_download": "تحميل",
    "label_due_date": "موعد التسليم",
    "label_new_list": "انشاء قائمة جديدة",
    "label_reminder": "تذكير",
    "rate_label": "هل تحب Wunderlist؟",
    "rate_app_button_yes": "الآن Wunderlist قيم",
    "placeholder_list_name": "اسم القائمة ",
    "placeholder_add_note": "أضف ملحوظة...",
    "placeholder_add_task_mobile": "أضف مهمة جديدة",
    "placeholder_new_list": "قائمة جديدة",
    "placeholder_remind_me": "ذكرني",
    "settings_visit_website": "قم بزيارة موقعنا ",
    "settings_get_help": "يرجي زيارة مركز الدعم",
    "settings_version": "الإصدار",
    "smart_list_inbox": "صندوق الوارد",
    "label_add_to_wunderlist": "Wunderlistاضافة الي",
    "public_list_label_logged_in_as": "تم التسجيل باسم",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "bg-BG": {
    "button_download": "Сваляне",
    "button_sign_in": "Вход",
    "button_log_out": "Изход",
    "button_download": "Сваляне",
    "label_due_date": "До Дата",
    "label_new_list": "Създай Нов Списък",
    "label_reminder": "Напомняне",
    "rate_label": "Харесва ли Ви Wunderlist?",
    "rate_app_button_yes": "Дай оценка на Wunderlist",
    "placeholder_list_name": "Фамилия",
    "placeholder_add_note": "Добави бележка...",
    "placeholder_add_task_mobile": "Добавете задача ...",
    "placeholder_new_list": "Нов Списък",
    "placeholder_remind_me": "Напомни ми",
    "settings_visit_website": "Посети ни",
    "settings_get_help": "Посетете Центъра за Поддръжка",
    "settings_version": "Версия",
    "smart_list_inbox": "Входяща Кутия",
    "label_add_to_wunderlist": "Добавете във Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "ca": {
    "button_download": "Descarrega",
    "button_sign_in": "Inicia sessió",
    "button_log_out": "Tanca la Sessió",
    "button_download": "Descarrega",
    "label_due_date": "Data de Venciment",
    "label_new_list": "Crea una nova llista",
    "label_reminder": "Recordatori",
    "rate_label": "T'agrada Wunderlist?",
    "rate_app_button_yes": "Valora Wunderlist",
    "placeholder_list_name": "Nom de la Llista",
    "placeholder_add_note": "Afegeix una nota...",
    "placeholder_add_task_mobile": "Afegeix un element...",
    "placeholder_new_list": "Nova Llista",
    "placeholder_remind_me": "Recorda-m'ho",
    "settings_visit_website": "Visita'ns",
    "settings_get_help": "Visita el Centre de Suport",
    "settings_version": "Versió",
    "smart_list_inbox": "Safata d'Entrada",
    "label_add_to_wunderlist": "Afegeix a Wunderlist",
    "public_list_label_logged_in_as": "Identificat com",
    "label_add_instantly_to": "Afegeix a l'instant a ...",
    "label_add_instantly_to_inbox": "Afegeix a l'instant a la bústia d'entrada",
    "label_add_link_url_to": "Afegeix l'enllaç´URL a ...",
    "label_add_link_url_to_inbox": "Afegeix l'enllaç URL a la bústia d'entrada",
    "label_add_audio_url_to": "Afegeix URL d'àudio a ...",
    "label_add_audio_url_to_inbox": "Afegeix URL d'àudio a la bústia d'entrada",
    "label_add_image_url_to": "Afegeix URL d'imatge a ...",
    "label_add_image_url_to_inbox": "Afegeix URL d'imatge a la bústia d'entrada",
    "label_add_video_url_to": "Afegeix URL de vídeo a ...",
    "label_add_video_url_to_inbox": "Afegeix URL de vídeo a la bústia d'entrada",
  },
  "cs-CZ": {
    "button_download": "Stáhnout",
    "button_sign_in": "Přihlášení",
    "button_log_out": "Odhlásit se",
    "button_download": "Stáhnout",
    "label_due_date": "Termín",
    "label_new_list": "Vytvořit nový seznam",
    "label_reminder": "Připomínka",
    "rate_label": "Líbí se vám Wunderlist?",
    "rate_app_button_yes": "Ohodnotit Wunderlist",
    "placeholder_list_name": "Název seznamu",
    "placeholder_add_note": "Přidat poznámku...",
    "placeholder_add_task_mobile": "Přidat položku...",
    "placeholder_new_list": "Nový seznam",
    "placeholder_remind_me": "Připomeň mi",
    "settings_visit_website": "Navštivte nás",
    "settings_get_help": "Navštivte Centrum Podpory",
    "settings_version": "Verze",
    "smart_list_inbox": "Doručené",
    "label_add_to_wunderlist": "Přidat do Wunderlistu",
    "public_list_label_logged_in_as": "Přihlášen(a) jako",
    "label_add_instantly_to": "Přidat ihned do ...",
    "label_add_instantly_to_inbox": "Přidat ihned do Doručené",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "da": {
    "button_download": "Download",
    "button_sign_in": "Log ind",
    "button_log_out": "Log ud",
    "button_download": "Download",
    "label_due_date": "Deadline",
    "label_new_list": "Opret ny liste",
    "label_reminder": "Påmindelse",
    "rate_label": "Er du glad for Wunderlist?",
    "rate_app_button_yes": "Bedøm Wunderlist",
    "placeholder_list_name": "Listenavn",
    "placeholder_add_note": "Tilføj en note...",
    "placeholder_add_task_mobile": "Tilføj en opgave...",
    "placeholder_new_list": "Ny liste",
    "placeholder_remind_me": "Påmind mig",
    "settings_visit_website": "Besøg os",
    "settings_get_help": "Besøg supportcenteret",
    "settings_version": "Version",
    "smart_list_inbox": "Indbakke",
    "label_add_to_wunderlist": "Føj til Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "de": {
    "button_download": "Herunterladen",
    "button_sign_in": "Anmelden",
    "button_log_out": "Abmelden",
    "button_download": "Herunterladen",
    "label_due_date": "Datum",
    "label_new_list": "Neue Liste hinzufügen",
    "label_reminder": "Erinnerung",
    "rate_label": "Gefällt dir Wunderlist?",
    "rate_app_button_yes": "Bewerte Wunderlist",
    "placeholder_list_name": "Listenname",
    "placeholder_add_note": "Notiz hinzufügen...",
    "placeholder_add_task_mobile": "Einen Eintrag hinzufügen...",
    "placeholder_new_list": "Neue Liste",
    "placeholder_remind_me": "Erinnere mich",
    "settings_visit_website": "Besuche uns",
    "settings_get_help": "Zum Support-Forum",
    "settings_version": "Version",
    "smart_list_inbox": "Eingang",
    "label_add_to_wunderlist": "Add to Wunderlist",
    "public_list_label_logged_in_as": "Angemeldet als",
    "label_add_instantly_to": "Sofort hinzufügen...",
    "label_add_instantly_to_inbox": "Sofort zur Eingangsliste hinzufügen",
    "label_add_link_url_to": "Link URL hinzufügen...",
    "label_add_link_url_to_inbox": "Link URL zur Eingangsliste hinzufügen",
    "label_add_audio_url_to": "Audio URL hinzufügen...",
    "label_add_audio_url_to_inbox": "Audio URL zur Eingangsliste hinzufügen",
    "label_add_image_url_to": "Bild URL hinzufügen...",
    "label_add_image_url_to_inbox": "Bild URL zur Eingangsliste hinzufügen",
    "label_add_video_url_to": "Video URL hinzufügen...",
    "label_add_video_url_to_inbox": "Video URL zur Eingangsliste hinzufügen",
  },
  "en": {
    "button_download": "Download",
    "button_sign_in": "Sign In",
    "button_log_out": "Sign Out",
    "button_download": "Download",
    "label_due_date": "Due Date",
    "label_new_list": "Create New List",
    "label_reminder": "Reminder",
    "rate_label": "Love Wunderlist?",
    "rate_app_button_yes": "Rate Wunderlist Now",
    "placeholder_list_name": "List Name",
    "placeholder_add_note": " Add a note...",
    "placeholder_add_task_mobile": "Add an item...",
    "placeholder_new_list": "New List",
    "placeholder_remind_me": "Remind me",
    "settings_visit_website": "Visit Us",
    "settings_get_help": "Visit the Support Center",
    "settings_version": "Version",
    "smart_list_inbox": "Inbox",
    "label_add_to_wunderlist": "Add to Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "es": {
    "button_download": "Descargar",
    "button_sign_in": "Entrar",
    "button_log_out": "Salir",
    "button_download": "Descargar",
    "label_due_date": "Fecha límite",
    "label_new_list": "Crear nueva lista",
    "label_reminder": "Recordatorio",
    "rate_label": "¿Le encanta Wunderlist?",
    "rate_app_button_yes": "Valorar Wunderlist",
    "placeholder_list_name": "Nombre de la lista",
    "placeholder_add_note": "Añadir una nota...",
    "placeholder_add_task_mobile": "Añadir un elemento...",
    "placeholder_new_list": "Nueva Lista",
    "placeholder_remind_me": "Recordar",
    "settings_visit_website": "Visita nuestra web",
    "settings_get_help": "Visita el Centro de Soporte",
    "settings_version": "Version",
    "smart_list_inbox": "Bandeja de entrada",
    "label_add_to_wunderlist": "Añadir a Wunderlist",
    "public_list_label_logged_in_as": "Conectado como",
    "label_add_instantly_to": "Añade al instante a ...",
    "label_add_instantly_to_inbox": "Añade al instante a \"Inbox\"",
    "label_add_link_url_to": "Añade el enlace URL a ...",
    "label_add_link_url_to_inbox": "Añade el enlace URL a \"Inbox\"",
    "label_add_audio_url_to": "Añade el enlace URL de audio a ...",
    "label_add_audio_url_to_inbox": "Añade el enlace URL de audio a \"Inbox\"",
    "label_add_image_url_to": "Añade el enlace URL de imagen a ...",
    "label_add_image_url_to_inbox": "Añade el enlace URL de imagen a \"Inbox\"",
    "label_add_video_url_to": "Añade el enlace URL de video a ...",
    "label_add_video_url_to_inbox": "Añade el enlace URL de video a \"Inbox\"",
  },
  "fa": {
    "button_download": "دانلود",
    "button_sign_in": "ورود",
    "button_log_out": "خروج",
    "button_download": "دانلود",
    "label_due_date": "تاریخ سررسید",
    "label_new_list": "ایجاد فهرست جدید",
    "label_reminder": "یادآور",
    "rate_label": "Love Wunderlist?",
    "rate_app_button_yes": "اکنون به واندرلیست امتیاز دهید",
    "placeholder_list_name": "List Name",
    "placeholder_add_note": " Add a note...",
    "placeholder_add_task_mobile": "افزودن...",
    "placeholder_new_list": "فهرست جدید",
    "placeholder_remind_me": "یادآوری کن",
    "settings_visit_website": "ما را ببینید",
    "settings_get_help": "مرکز پشتیبانی ما را ببینید",
    "settings_version": "نسخه",
    "smart_list_inbox": "صندوق ورودی",
    "label_add_to_wunderlist": "Add to Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "افزودن مستقیم به ...",
    "label_add_instantly_to_inbox": "افزودن مستقیم به صندوق ورودی",
    "label_add_link_url_to": "افزودن آدرس پیوند به ...",
    "label_add_link_url_to_inbox": "افزودن آدرس پیوند به صندوق ورودی",
    "label_add_audio_url_to": "افزودن آدرس صوت به ...",
    "label_add_audio_url_to_inbox": "افزودن آدرس صوت به صندوق ورودی",
    "label_add_image_url_to": "افزودن آدرس تصویر به ...",
    "label_add_image_url_to_inbox": "افزودن آدرس تصویر به صندوق ورودی",
    "label_add_video_url_to": "افزودن آدرس ویدئو به ...",
    "label_add_video_url_to_inbox": "افزودن آدرس ویدئو به صندوق ورودی",
  },
  "fi": {
    "button_download": "Lataa",
    "button_sign_in": "Kirjaudu sisään",
    "button_log_out": "Kirjaudu ulos",
    "button_download": "Lataa",
    "label_due_date": "Ajankohta",
    "label_new_list": "Luo uusi lista",
    "label_reminder": "Muistutus",
    "rate_label": "Pidätkö Wunderlististä?",
    "rate_app_button_yes": "Anna Wunderlistille arvosanasi",
    "placeholder_list_name": "Luettelon nimi",
    "placeholder_add_note": "Lisää muistiinpano...",
    "placeholder_add_task_mobile": "Lisää uusi...",
    "placeholder_new_list": "Uusi lista",
    "placeholder_remind_me": "Muistuta minua",
    "settings_visit_website": "Käy luonamme",
    "settings_get_help": "Käy Tukikeskuksessamme",
    "settings_version": "Versio",
    "smart_list_inbox": "Saapuneet",
    "label_add_to_wunderlist": "Lisää Wunderlistiin",
    "public_list_label_logged_in_as": "Kirjautuneena tunnuksella",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "fr": {
    "button_download": "Télécharger",
    "button_sign_in": "Connexion",
    "button_log_out": "Se déconnecter",
    "button_download": "Télécharger",
    "label_due_date": "Échéance",
    "label_new_list": "Créer une nouvelle liste",
    "label_reminder": "Rappel",
    "rate_label": "Vous aimez Wunderlist?",
    "rate_app_button_yes": "Noter Wunderlist",
    "placeholder_list_name": "Nom de la liste",
    "placeholder_add_note": "Ajouter une remarque...",
    "placeholder_add_task_mobile": "Ajouter une tâche...",
    "placeholder_new_list": "Nouvelle liste",
    "placeholder_remind_me": "Me rappeler",
    "settings_visit_website": "Nous rendre visite",
    "settings_get_help": "Visiter le Centre d'aide",
    "settings_version": "Version",
    "smart_list_inbox": "Boîte de réception",
    "label_add_to_wunderlist": "Ajouter à Wunderlist",
    "public_list_label_logged_in_as": "Se connecter en tant que",
    "label_add_instantly_to": "Ajouter immédiatement à ...",
    "label_add_instantly_to_inbox": "Ajouter immédiatement à la boîte de réception",
    "label_add_link_url_to": "Ajouter immédiatement l'URL du lien à ...",
    "label_add_link_url_to_inbox": "Ajouter immédiatement l'adresse du lien à la boîte de réception",
    "label_add_audio_url_to": "Ajouter immédiatement l'URL du fichier son à ...",
    "label_add_audio_url_to_inbox": "Ajouter immédiatement l'URL du fichier son à la boîte de réception",
    "label_add_image_url_to": "Ajouter immédiatement l'URL de l'image à ...",
    "label_add_image_url_to_inbox": "Ajouter immédiatement l'URL de l'image à la boîte de réception",
    "label_add_video_url_to": "Ajouter immédiatement l'URL de la vidéo à ...",
    "label_add_video_url_to_inbox": "Ajouter immédiatement l'URL de la vidéo à la boîte de réception",
  },
  "grk": {
    "button_download": "Λήψη",
    "button_sign_in": "Είσσοδς",
    "button_log_out": "Αποσύνδεση",
    "button_download": "Λήψη",
    "label_due_date": "Καταληκτική Ημερομηνία ",
    "label_new_list": "Δημιουργία Νέας Λίστας",
    "label_reminder": "Υπενθύμιση",
    "rate_label": "Σας αρέσει το Wunderlist;",
    "rate_app_button_yes": "Βαθμολόγηση του Wunderlist τώρα",
    "placeholder_list_name": "Όνομα λίστας",
    "placeholder_add_note": "Προσθέστε μια σημείωση...",
    "placeholder_add_task_mobile": "Προσθήκη στοιχείου...",
    "placeholder_new_list": "Νεα Λίστα",
    "placeholder_remind_me": "Υπενθύμισέ μου",
    "settings_visit_website": "Επισκεφτείτε μας",
    "settings_get_help": "Επισκεψη του Κεντρου υποστηριξης",
    "settings_version": "Έκδοση",
    "smart_list_inbox": "Εισερχόμενα",
    "label_add_to_wunderlist": "Προσθήκη στο Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "he": {
    "button_download": "מוריד",
    "button_sign_in": "הכנס",
    "button_log_out": "התנתק",
    "button_download": "מוריד",
    "label_due_date": "תאריך ביצוע",
    "label_new_list": "צור רשימה חדשה",
    "label_reminder": "תזכורת",
    "rate_label": "אוהב את וונדרליסט?",
    "rate_app_button_yes": "דרג את וונדרליסט",
    "placeholder_list_name": "שם הרשימה",
    "placeholder_add_note": "הוסף הערה...",
    "placeholder_add_task_mobile": "הוסף משימה...",
    "placeholder_new_list": "רשימה חדשה",
    "placeholder_remind_me": "תזכיר לי",
    "settings_visit_website": "בקר אותנו",
    "settings_get_help": "בקר במוקד התמיכה",
    "settings_version": "גרסה",
    "smart_list_inbox": " דואר נכנס",
    "label_add_to_wunderlist": "הוסף לוונדרליסט",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "hu-HU": {
    "button_download": "Letöltés",
    "button_sign_in": "Bejelentkezés",
    "button_log_out": "Kijelentkezés",
    "button_download": "Letöltés",
    "label_due_date": "Határidő",
    "label_new_list": "Új lista készítése",
    "label_reminder": "Emlékeztető",
    "rate_label": "Tetszik a Wunderlist?",
    "rate_app_button_yes": "Értékeld a Wunderlist-et",
    "placeholder_list_name": "Lista neve",
    "placeholder_add_note": "Megjegyzés hozzáadása...",
    "placeholder_add_task_mobile": "Új teendő hozzáadása...",
    "placeholder_new_list": "Új lista",
    "placeholder_remind_me": "Emlékeztess",
    "settings_visit_website": "Weboldalunk",
    "settings_get_help": "Támogatási központ megtekintése",
    "settings_version": "Verzió",
    "smart_list_inbox": "Beérkező",
    "label_add_to_wunderlist": "Hozzáadás a Wunderlist-hez",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "is-IS": {
    "button_download": "Hlaða niður",
    "button_sign_in": "Innskrá",
    "button_log_out": "Útskrá",
    "button_download": "Hlaða niður",
    "label_due_date": "Loka dagsetning",
    "label_new_list": "Stofna nýjan lista",
    "label_reminder": "Áminning",
    "rate_label": "Elskar þú Wunderlist?",
    "rate_app_button_yes": "Gefa Wunderlist einkunn",
    "placeholder_list_name": "Nafn lista",
    "placeholder_add_note": " Add a note...",
    "placeholder_add_task_mobile": "Bæta við nýjum lið...",
    "placeholder_new_list": "Nýr listi",
    "placeholder_remind_me": "Fá áminningu",
    "settings_visit_website": "Visit Us",
    "settings_get_help": "Kíkja á Hjálpartorgið",
    "settings_version": "Útgáfa",
    "smart_list_inbox": "Innhólf",
    "label_add_to_wunderlist": "Bæta við í Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "it": {
    "button_download": "Scarica",
    "button_sign_in": "Accedi",
    "button_log_out": "Disconnettiti",
    "button_download": "Scarica",
    "label_due_date": "Data di Scadenza",
    "label_new_list": "Crea una nuova lista",
    "label_reminder": "Promemoria",
    "rate_label": "Ti piace Wunderlist?",
    "rate_app_button_yes": "Vota Wunderlist",
    "placeholder_list_name": "Nome della Lista",
    "placeholder_add_note": "Aggiungi nota…",
    "placeholder_add_task_mobile": "Aggiungi un'attività...",
    "placeholder_new_list": "Nuova Lista",
    "placeholder_remind_me": "Ricordamelo",
    "settings_visit_website": "Vieni a trovarci",
    "settings_get_help": "Visita il Centro Supporto",
    "settings_version": "Versione",
    "smart_list_inbox": "Inbox",
    "label_add_to_wunderlist": "Aggiungi a Wunderlist",
    "public_list_label_logged_in_as": "Accesso eseguito come",
    "label_add_instantly_to": "Aggiungi subito a ...",
    "label_add_instantly_to_inbox": "Aggiungi subito alla Inbox",
    "label_add_link_url_to": "Aggiungi link a ...",
    "label_add_link_url_to_inbox": "Aggiungi link alla Inbox",
    "label_add_audio_url_to": "Aggiungi link audio alla Inbox",
    "label_add_audio_url_to_inbox": "Aggiungi link audio alla Inbox",
    "label_add_image_url_to": "Aggiungi URL immagine a ...",
    "label_add_image_url_to_inbox": "Aggiungi URL immagine alla Inbox",
    "label_add_video_url_to": "Aggiungi URL video a ...",
    "label_add_video_url_to_inbox": "Aggiungi URL video alla Inbox",
  },
  "ja-JP": {
    "button_download": "ダウンロード",
    "button_sign_in": "サインイン",
    "button_log_out": "サインアウト",
    "button_download": "ダウンロード",
    "label_due_date": "期限日",
    "label_new_list": "リストを新規作成",
    "label_reminder": "リマインダー",
    "rate_label": "Wunderlistを気に入っていただけましたか？",
    "rate_app_button_yes": "Wunderlistを評価",
    "placeholder_list_name": "リストの名前",
    "placeholder_add_note": "メモを追加",
    "placeholder_add_task_mobile": "アイテムを追加…",
    "placeholder_new_list": "新規リスト",
    "placeholder_remind_me": "リマインダーを設定",
    "settings_visit_website": "ウェブサイトへ",
    "settings_get_help": "サポートセンターへ",
    "settings_version": "バージョン",
    "smart_list_inbox": "受信トレイ",
    "label_add_to_wunderlist": "Wunderlistに追加する",
    "public_list_label_logged_in_as": "サインインする",
    "label_add_instantly_to": "簡単追加する",
    "label_add_instantly_to_inbox": "受信トレイに簡単追加する",
    "label_add_link_url_to": "URLを追加する",
    "label_add_link_url_to_inbox": "URLを受信トレイに追加する",
    "label_add_audio_url_to": "音声URLを追加する",
    "label_add_audio_url_to_inbox": "音声URLを受信トレイに追加する",
    "label_add_image_url_to": "画像URLを追加する",
    "label_add_image_url_to_inbox": "画像URLを受信トレイに追加する",
    "label_add_video_url_to": "ビデオURLを追加する",
    "label_add_video_url_to_inbox": "ビデオURLを受信トレイに追加する",
  },
  "ka": {
    "button_download": "გადმოწერა",
    "button_sign_in": "შესვლა",
    "button_log_out": "გამოსვლა",
    "button_download": "გადმოწერა",
    "label_due_date": "შესრულების ვადა",
    "label_new_list": "ახალი სიის შექმნა",
    "label_reminder": "შეხსენება",
    "rate_label": "Love Wunderlist?",
    "rate_app_button_yes": "Wunderlist-ის შეფასება",
    "placeholder_list_name": "List Name",
    "placeholder_add_note": " Add a note...",
    "placeholder_add_task_mobile": "ელემენტის დამატება...",
    "placeholder_new_list": "ახალი სია",
    "placeholder_remind_me": "შეხსენება",
    "settings_visit_website": "Visit Us",
    "settings_get_help": "ეწვიეთ მხარდაჭერის ცენტრს",
    "settings_version": "ვერსია",
    "smart_list_inbox": "შემომავალი",
    "label_add_to_wunderlist": "Add to Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "ko": {
    "button_download": "다운로드",
    "button_sign_in": "로그인",
    "button_log_out": "로그아웃",
    "button_download": "다운로드",
    "label_due_date": "기한",
    "label_new_list": "새 목록 작성",
    "label_reminder": "미리 알림",
    "rate_label": "Wunderlist가 마음에 드십니까?",
    "rate_app_button_yes": "지금 Wunderlist 평가하기",
    "placeholder_list_name": "목록 이름",
    "placeholder_add_note": " 메모 추가...",
    "placeholder_add_task_mobile": "항목 추가",
    "placeholder_new_list": "새 목록",
    "placeholder_remind_me": "미리 알리기",
    "settings_visit_website": "방문하기",
    "settings_get_help": "고객 지원 센터에 방문하기",
    "settings_version": "버전",
    "smart_list_inbox": "보관함",
    "label_add_to_wunderlist": "Wunderlist에 추가",
    "public_list_label_logged_in_as": "로그인 이름",
    "label_add_instantly_to": "즉시 추가...",
    "label_add_instantly_to_inbox": "수신함에 즉시 추가 ",
    "label_add_link_url_to": "링크 URL 추가 ...",
    "label_add_link_url_to_inbox": "수신함에 링크 URL 추가",
    "label_add_audio_url_to": "오디오 URL 추가...",
    "label_add_audio_url_to_inbox": "수신함에 오디오 URL 추가  ",
    "label_add_image_url_to": "이미지 URL 추가...",
    "label_add_image_url_to_inbox": "수신함에 이미지 URL 추가 ",
    "label_add_video_url_to": "비디오 URL 추가...",
    "label_add_video_url_to_inbox": "수신함에 비디오 URL 추가 ",
  },
  "mt": {
    "button_download": "Iddawnlodja",
    "button_sign_in": "Idħol",
    "button_log_out": "Oħroġ",
    "button_download": "Iddawnlodja",
    "label_due_date": "Deadline",
    "label_new_list": "Oħloq Lista Ġdida",
    "label_reminder": "Tifkira",
    "rate_label": "Sodissfatt b'Wunderlist?",
    "rate_app_button_yes": "Irrejtja 'l Wunderlist",
    "placeholder_list_name": "Isem tal-Lista",
    "placeholder_add_note": "Żid nota...",
    "placeholder_add_task_mobile": "Żid item...",
    "placeholder_new_list": "Lista Ġdida",
    "placeholder_remind_me": "Fakkarni",
    "settings_visit_website": "Żurna",
    "settings_get_help": "Żur iċ-Ċentru ta' Sapport",
    "settings_version": "Verżjoni",
    "smart_list_inbox": "Inbox",
    "label_add_to_wunderlist": "Add to Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "my": {
    "button_download": "ဒေါင်းလုတ်",
    "button_sign_in": "ဝင်မည်",
    "button_log_out": "ထွက်မည်",
    "button_download": "ဒေါင်းလုတ်",
    "label_due_date": "ပြည့်မည့်ရက်စွဲ",
    "label_new_list": "အစီအစဉ်အသစ်ဖန်တီးမည်",
    "label_reminder": "သတိပေးချက်",
    "rate_label": "Love Wunderlist?",
    "rate_app_button_yes": "Wunderlist ကိုအမှတ်ပေးမည်",
    "placeholder_list_name": "List Name",
    "placeholder_add_note": " Add a note...",
    "placeholder_add_task_mobile": "အမျိုအစားတစ်ခုကိုထည့်မည်",
    "placeholder_new_list": "စာရင်းအသစ်",
    "placeholder_remind_me": "ကျွန်ုပ်ကိုသတိပေးပါ",
    "settings_visit_website": "ကျွန်ုပ်တို့ဆီလာရောက်လည်ပတ်ပါ",
    "settings_get_help": "ထောက်ပံ့ပေးသည့်စင်တာသို့လည်ပတ်မည်",
    "settings_version": "ဗားရှင်း",
    "smart_list_inbox": "Inbox",
    "label_add_to_wunderlist": "Add to Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "nl": {
    "button_download": "Download",
    "button_sign_in": "Aanmelden",
    "button_log_out": "Afmelden",
    "button_download": "Download",
    "label_due_date": "Vervaldatum",
    "label_new_list": "Nieuwe lijst aanmaken",
    "label_reminder": "Herinnering",
    "rate_label": "Gek op Wunderlist?",
    "rate_app_button_yes": "Beoordeel Wunderlist nu",
    "placeholder_list_name": "Lijst naam",
    "placeholder_add_note": "Voeg een notitie toe...",
    "placeholder_add_task_mobile": "Een taak toevoegen...",
    "placeholder_new_list": "Nieuwe lijst",
    "placeholder_remind_me": "Herinner mij",
    "settings_visit_website": "Bezoek Ons",
    "settings_get_help": "Bezoek het Support Center",
    "settings_version": "Versie",
    "smart_list_inbox": "Postvak in",
    "label_add_to_wunderlist": "Toevoegen aan Wunderlist",
    "public_list_label_logged_in_as": "Ingelogd als",
    "label_add_instantly_to": "Voeg onmiddellijk toe aan ...",
    "label_add_instantly_to_inbox": "Voeg onmiddellijk toe aan postvak in",
    "label_add_link_url_to": "Voeg link-URL toe aan ...",
    "label_add_link_url_to_inbox": "Voeg link-URL toe aan postvak in",
    "label_add_audio_url_to": "Voeg audio-URL toe aan ...",
    "label_add_audio_url_to_inbox": "Voeg audio-URL toe aan postvak in",
    "label_add_image_url_to": "Voeg afbeelding-URL toe aan ...",
    "label_add_image_url_to_inbox": "Voeg afbeelding-URL toe aan postvak in",
    "label_add_video_url_to": "Voeg video-URL toe aan ...",
    "label_add_video_url_to_inbox": "Voeg video-URL toe aan postvak in",
  },
  "no": {
    "button_download": "Last ned",
    "button_sign_in": "Logg inn",
    "button_log_out": "Logg ut",
    "button_download": "Last ned",
    "label_due_date": "Forfallsdato",
    "label_new_list": "Lag ny liste",
    "label_reminder": "Påminnelse",
    "rate_label": "Elsker du Wunderlist?",
    "rate_app_button_yes": "Vurdér Wunderlist",
    "placeholder_list_name": "Listenavn",
    "placeholder_add_note": "Legg til et notat...",
    "placeholder_add_task_mobile": "Legg til element...",
    "placeholder_new_list": "Ny liste",
    "placeholder_remind_me": "Gi meg påminnelse",
    "settings_visit_website": "Besøk oss",
    "settings_get_help": "Besøk brukerstøttesenteret",
    "settings_version": "Versjon",
    "smart_list_inbox": "Innboks",
    "label_add_to_wunderlist": "Legg til Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "pl-PL": {
    "button_download": "Pobierz",
    "button_sign_in": "Zaloguj się",
    "button_log_out": "Wyloguj",
    "button_download": "Pobierz",
    "label_due_date": "Data ukończenia",
    "label_new_list": "Utwórz listę",
    "label_reminder": "Przypomnienie",
    "rate_label": "Podoba Ci się Wunderlist?",
    "rate_app_button_yes": "Oceń Wunderlist",
    "placeholder_list_name": "Nazwa listy",
    "placeholder_add_note": "Dodaj notatkę...",
    "placeholder_add_task_mobile": "Dodaj element...",
    "placeholder_new_list": "Nowa lista",
    "placeholder_remind_me": "Przypomnij mi",
    "settings_visit_website": "Odwiedź naszą stronę",
    "settings_get_help": "Odwiedź Centrum Pomocy",
    "settings_version": "Wersja",
    "smart_list_inbox": "Skrzynka odbiorcza",
    "label_add_to_wunderlist": "Dodaj do Wunderlist",
    "public_list_label_logged_in_as": "Zalogowano jako",
    "label_add_instantly_to": "Szybko dodaj do...",
    "label_add_instantly_to_inbox": "Szybko dodaj do Skrzynki odbiorczej",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "pt-BR": {
    "button_download": "Download",
    "button_sign_in": "Entrar",
    "button_log_out": "Sair",
    "button_download": "Download",
    "label_due_date": "Data Limite",
    "label_new_list": "Criar Nova Lista",
    "label_reminder": "Lembrete",
    "rate_label": "Adora o Wunderlist?",
    "rate_app_button_yes": "Avaliar o Wunderlist",
    "placeholder_list_name": "Nome da Lista",
    "placeholder_add_note": " Adicionar uma anotação...",
    "placeholder_add_task_mobile": "Adicione um item...",
    "placeholder_new_list": "Nova Lista",
    "placeholder_remind_me": "Lembrar",
    "settings_visit_website": "Visite-nos",
    "settings_get_help": "Visite a central de suporte",
    "settings_version": "Versão",
    "smart_list_inbox": "Caixa de Entrada",
    "label_add_to_wunderlist": "Adicionar ao Wunderlist",
    "public_list_label_logged_in_as": "Logado como",
    "label_add_instantly_to": "Adicionar imediatamente em...",
    "label_add_instantly_to_inbox": "Adicionar imediatamente à Caixa de Entrada",
    "label_add_link_url_to": "Adicionar URL do link em...",
    "label_add_link_url_to_inbox": "Adicionar URL do link à Caixa de Entrada",
    "label_add_audio_url_to": "Adicionar URL de áudio em...",
    "label_add_audio_url_to_inbox": "Adicionar URL de áudio à Caixa de Entrada",
    "label_add_image_url_to": "Adicionar URL da imagem em...",
    "label_add_image_url_to_inbox": "Adicionar URL da imagem à Caixa de Entrada",
    "label_add_video_url_to": "Adicionar URL do vídeo em...",
    "label_add_video_url_to_inbox": "Adicionar URL do vídeo à Caixa de Entrada",
  },
  "pt-PT": {
    "button_download": "Download",
    "button_sign_in": "Iniciar sessão",
    "button_log_out": "Terminar sessão",
    "button_download": "Download",
    "label_due_date": "Data de conclusão",
    "label_new_list": "Crear Lista Nova",
    "label_reminder": "Lembrete",
    "rate_label": "Gosta da Wunderlist?",
    "rate_app_button_yes": "Classifique Wunderlist",
    "placeholder_list_name": "Nome da lista",
    "placeholder_add_note": "Adicione uma nota...",
    "placeholder_add_task_mobile": "Adicione um elemento…",
    "placeholder_new_list": "Nova lista",
    "placeholder_remind_me": "Lembrar-me",
    "settings_visit_website": "Visite-nos",
    "settings_get_help": "Visite o Centro de Suporte",
    "settings_version": "Versão",
    "smart_list_inbox": "Caixa de entrada",
    "label_add_to_wunderlist": "Adicionar à Wunderlist",
    "public_list_label_logged_in_as": "Registado como",
    "label_add_instantly_to": "Adicione de imediato a ...",
    "label_add_instantly_to_inbox": "Adicione de imediato à Caixa de Entrada",
    "label_add_link_url_to": "Adicionar o endereço da ligação a ...",
    "label_add_link_url_to_inbox": "Adicione o endereço da ligação à Caixa de Entrada",
    "label_add_audio_url_to": "Adicione o endereço do áudio a ...",
    "label_add_audio_url_to_inbox": "Adicione o endereço do áudio à Caixa de Entrada",
    "label_add_image_url_to": "Adicione o endereço da imagem a ...",
    "label_add_image_url_to_inbox": "Adicione o endereço da imagem à Caixa de Entrada",
    "label_add_video_url_to": "Adicione o endereço do vídeo a ...",
    "label_add_video_url_to_inbox": "Adicione o endereço do vídeo à Caixa de Entrada",
  },
  "ro": {
    "button_download": "Descărcați",
    "button_sign_in": "Înregistrare",
    "button_log_out": "Deconectare",
    "button_download": "Descărcați",
    "label_due_date": "Termen limită",
    "label_new_list": "Creează o listă nouă",
    "label_reminder": "Alertă",
    "rate_label": "Îți place Wunderlist?",
    "rate_app_button_yes": "Votează Wunderlist",
    "placeholder_list_name": "Denumire listă",
    "placeholder_add_note": "Adaugă o notă",
    "placeholder_add_task_mobile": "Adaugă o sarcină...",
    "placeholder_new_list": "Listă nouă",
    "placeholder_remind_me": "Amintește-mi",
    "settings_visit_website": "Vizitează-ne",
    "settings_get_help": "Vizitează centrul de asistență",
    "settings_version": "Versiune",
    "smart_list_inbox": "Inbox",
    "label_add_to_wunderlist": "Adaugă în Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "ru": {
    "button_download": "Загрузить",
    "button_sign_in": "Войти",
    "button_log_out": "Выйти",
    "button_download": "Загрузить",
    "label_due_date": "Срок выполнения",
    "label_new_list": "Создать новый список",
    "label_reminder": "Напоминание",
    "rate_label": "Нравится Wunderlist?",
    "rate_app_button_yes": "Оценить Wunderlist",
    "placeholder_list_name": "Название",
    "placeholder_add_note": "Добавить заметку...",
    "placeholder_add_task_mobile": "Добавить задачу...",
    "placeholder_new_list": "Новый список",
    "placeholder_remind_me": "Напомнить",
    "settings_visit_website": "Посетить нас",
    "settings_get_help": "Посетить Центр поддержки",
    "settings_version": "Версия",
    "smart_list_inbox": "Входящие",
    "label_add_to_wunderlist": "Добавить в Wunderlist",
    "public_list_label_logged_in_as": "Вход выполнен под именем",
    "label_add_instantly_to": "Мгновенно добавить в...",
    "label_add_instantly_to_inbox": "Мгновенно добавить в папку \"Входящие\"",
    "label_add_link_url_to": "Добавить ссылку на URL-адрес в ...",
    "label_add_link_url_to_inbox": "Добавить ссылку на URL-адрес в папку \"Входящие\"",
    "label_add_audio_url_to": "Добавить URL-адрес звука в ...",
    "label_add_audio_url_to_inbox": "Добавить URL-адрес звука в папку \"Входящие\"",
    "label_add_image_url_to": "Добавить URL-адрес изображения в ...",
    "label_add_image_url_to_inbox": "Добавить URL-адрес изображения в папку \"Входящие\"",
    "label_add_video_url_to": "Добавить URL-адрес видео в ...",
    "label_add_video_url_to_inbox": "Добавить URL-адрес видео в папку \"Входящие\"",
  },
  "sk-SK": {
    "button_download": "Stiahnuť",
    "button_sign_in": "Prihlásiť sa",
    "button_log_out": "Odhlásiť sa",
    "button_download": "Stiahnuť",
    "label_due_date": "Termín dokončenia",
    "label_new_list": "Vytvoriť nový zoznam",
    "label_reminder": "Pripomienka",
    "rate_label": "Máte radi Wunderlist?",
    "rate_app_button_yes": "Ohodnoťte Wunderlist teraz",
    "placeholder_list_name": "Názov zoznamu",
    "placeholder_add_note": "Pridať poznámku...",
    "placeholder_add_task_mobile": "Pridať položku...",
    "placeholder_new_list": "Nový zoznam",
    "placeholder_remind_me": "Upozorni ma",
    "settings_visit_website": "Navštívte nás",
    "settings_get_help": "Navštívte Centrum podpory",
    "settings_version": "Verzia",
    "smart_list_inbox": "Prijaté",
    "label_add_to_wunderlist": "Pridať do Wunderlistu",
    "public_list_label_logged_in_as": "Prihlásený ako",
    "label_add_instantly_to": "Pridať okamžite do ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "sl-SI": {
    "button_download": "Prenesi",
    "button_sign_in": "Vpis\n",
    "button_log_out": "Izpis",
    "button_download": "Prenesi",
    "label_due_date": "Datum zapadlosti",
    "label_new_list": "Ustvari nov seznam",
    "label_reminder": "Opomnik",
    "rate_label": "Love Wunderlist?",
    "rate_app_button_yes": "Oceni Wunderlist",
    "placeholder_list_name": "List Name",
    "placeholder_add_note": " Add a note...",
    "placeholder_add_task_mobile": "Dodaj opravilo...",
    "placeholder_new_list": "Nov seznam",
    "placeholder_remind_me": "Opomni me",
    "settings_visit_website": "Visit Us",
    "settings_get_help": "Obišči center za podporo",
    "settings_version": "Različica",
    "smart_list_inbox": "Prejeto",
    "label_add_to_wunderlist": "Dodaj v Wunderlist",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "sq-AL": {
    "button_download": "Shkarkoni",
    "button_sign_in": "Kyçuni",
    "button_log_out": "Dilni",
    "button_download": "Shkarkoni",
    "label_due_date": "Data e afatit",
    "label_new_list": "Krijoni listë të re",
    "label_reminder": "Përkujtues",
    "rate_label": "E pëlqeni Wunderlist?",
    "rate_app_button_yes": "Vlerësojeni Wunderlist tani",
    "placeholder_list_name": "Emri i listës",
    "placeholder_add_note": "Shtoni një shënim...",
    "placeholder_add_task_mobile": "Shtoni një artikull...",
    "placeholder_new_list": "Listë e re",
    "placeholder_remind_me": "Më kujto",
    "settings_visit_website": "Na vizitoni",
    "settings_get_help": "Vizitoni Qendrën e Mbështetjes",
    "settings_version": "Versioni",
    "smart_list_inbox": "Kuti Postare",
    "label_add_to_wunderlist": "Shtoni në Wunderlist",
    "public_list_label_logged_in_as": "Kyçur si",
    "label_add_instantly_to": "Shto menjëherë në ...",
    "label_add_instantly_to_inbox": "Shto menjëherë në Kutinë Postare",
    "label_add_link_url_to": "Shto lidhjen URL në ...",
    "label_add_link_url_to_inbox": "Shto lidhjen URL në Kutinë Postare",
    "label_add_audio_url_to": "Shto URL-n e audios në ...",
    "label_add_audio_url_to_inbox": "Shto URL-n e audios në Kutinë Postare",
    "label_add_image_url_to": "Shto URL-n e imazhit në ...",
    "label_add_image_url_to_inbox": "Shto URL-n e imazhit në Kutinë Postare",
    "label_add_video_url_to": "Shto URL-n e videos në ...",
    "label_add_video_url_to_inbox": "Shto URL-n e videos në Kutinë Postare",
  },
  "sv": {
    "button_download": "Ladda ner",
    "button_sign_in": "Logga in",
    "button_log_out": "Logga ut",
    "button_download": "Ladda ner",
    "label_due_date": "Förfallodag",
    "label_new_list": "Skapa ny lista",
    "label_reminder": "Påminnelse",
    "rate_label": "Gillar du Wunderlist?",
    "rate_app_button_yes": "Betygsätt Wunderlist",
    "placeholder_list_name": "Listnamn",
    "placeholder_add_note": "Lägg till anteckning...",
    "placeholder_add_task_mobile": "Lägg till ny uppgift...",
    "placeholder_new_list": "Ny lista",
    "placeholder_remind_me": "Påminn mig",
    "settings_visit_website": "Besök oss",
    "settings_get_help": "Besök Supportcenter",
    "settings_version": "Version",
    "smart_list_inbox": "Inkorg",
    "label_add_to_wunderlist": "Lägg till i Wunderlist",
    "public_list_label_logged_in_as": "Inloggad som",
    "label_add_instantly_to": "Lägg omedelbart till…",
    "label_add_instantly_to_inbox": "Lägg till direkt i Inkorgen",
    "label_add_link_url_to": "Lägg till URL till…",
    "label_add_link_url_to_inbox": "Lägg till URL-länk till Inkorgen",
    "label_add_audio_url_to": "Lägg till ljud-URL till…",
    "label_add_audio_url_to_inbox": "Lägg till ljud-URL till Inkorgen",
    "label_add_image_url_to": "Lätt till bild-URL till…",
    "label_add_image_url_to_inbox": "Lägg till bild-URL till Inkorgen",
    "label_add_video_url_to": "Lägg till video-URL till…",
    "label_add_video_url_to_inbox": "Lägg till video-URL till Inkorgen",
  },
  "th-TH": {
    "button_download": "ดาวน์โหลด",
    "button_sign_in": "เข้าสู่ระบบ",
    "button_log_out": "ออกจากระบบ",
    "button_download": "ดาวน์โหลด",
    "label_due_date": "วันส่งงาน",
    "label_new_list": "สร้างรายการใหม่",
    "label_reminder": "การแจ้งเตือน",
    "rate_label": "ชอบ Wunderlist?",
    "rate_app_button_yes": "ให้คะแนน Wunderlist ตอนนี้",
    "placeholder_list_name": "ชื่อรายการ",
    "placeholder_add_note": "เพิ่มบันทึก...",
    "placeholder_add_task_mobile": "เพิ่มงานใหม่..",
    "placeholder_new_list": "รายการใหม่",
    "placeholder_remind_me": "เตือนฉัน",
    "settings_visit_website": "เยี่ยมชมเรา",
    "settings_get_help": "เยี่ยมชมศูนย์ช่วยเหลือ",
    "settings_version": "เวอร์ชั่น",
    "smart_list_inbox": "กล่องขาเข้า",
    "label_add_to_wunderlist": "เพิ่มเข้า Wunderlist",
    "public_list_label_logged_in_as": "เข้าสู่ระบบในชื่อ",
    "label_add_instantly_to": "เพิ่มทันทีใน ...",
    "label_add_instantly_to_inbox": "เพิ่มทันทีในกล่องขาเข้า",
    "label_add_link_url_to": "เพิ่มที่อยู่ลิงก์ใน ...",
    "label_add_link_url_to_inbox": "เพิ่มที่อยู่ลิงก์ทันทีในกล่องขาเข้า",
    "label_add_audio_url_to": "เพิ่มที่อยู่ไฟล์เสียงใน ...",
    "label_add_audio_url_to_inbox": "เพิ่มที่อยู่ไฟล์เสียงในกล่องขาเข้า",
    "label_add_image_url_to": "เพิ่มที่อยู่รูปภาพใน ...",
    "label_add_image_url_to_inbox": "เพิ่มที่อยู่รูปภาพในกล่องขาเข้า",
    "label_add_video_url_to": "เพิ่มที่อยู่วิดีโอใน ...",
    "label_add_video_url_to_inbox": "เพิ่มที่อยู่วิดีโอในกล่องขาเข้า",
  },
  "tr-TR": {
    "button_download": "İndir",
    "button_sign_in": "Giriş Yap",
    "button_log_out": "Çıkış Yap",
    "button_download": "İndir",
    "label_due_date": "Bitiş Tarihi",
    "label_new_list": "Yeni Liste Oluştur",
    "label_reminder": "Hatırlatıcı",
    "rate_label": "Wunderlist'i Sevdiniz mi?",
    "rate_app_button_yes": "Wunderlist'e Oy Ver",
    "placeholder_list_name": "Liste Adı",
    "placeholder_add_note": "Bir not ekle...",
    "placeholder_add_task_mobile": "Bir öğe ekle...",
    "placeholder_new_list": "Yeni Liste",
    "placeholder_remind_me": "Bana hatırlat",
    "settings_visit_website": "Bizi Ziyaret Edin",
    "settings_get_help": "Destek Merkezi'ni ziyaret Edin.",
    "settings_version": "Sürüm",
    "smart_list_inbox": "Gelen Kutusu",
    "label_add_to_wunderlist": "Wunderlist'e ekle",
    "public_list_label_logged_in_as": "Signed in as",
    "label_add_instantly_to": "Add instantly to ...",
    "label_add_instantly_to_inbox": "Add instantly to Inbox",
    "label_add_link_url_to": "Add link URL to ...",
    "label_add_link_url_to_inbox": "Add link URL to Inbox",
    "label_add_audio_url_to": "Add audio URL to ...",
    "label_add_audio_url_to_inbox": "Add audio URL to Inbox",
    "label_add_image_url_to": "Add image URL to ...",
    "label_add_image_url_to_inbox": "Add image URL to Inbox",
    "label_add_video_url_to": "Add video URL to ...",
    "label_add_video_url_to_inbox": "Add video URL to Inbox",
  },
  "zh-CN": {
    "button_download": "下载",
    "button_sign_in": "登录",
    "button_log_out": "登出",
    "button_download": "下载",
    "label_due_date": "到期日",
    "label_new_list": "创建新清单",
    "label_reminder": "提醒",
    "rate_label": "喜欢奇妙清单？",
    "rate_app_button_yes": "立即评价我们",
    "placeholder_list_name": "清单名称",
    "placeholder_add_note": "添加备注...",
    "placeholder_add_task_mobile": "添加一个任务...",
    "placeholder_new_list": "新清单",
    "placeholder_remind_me": "提醒我",
    "settings_visit_website": "访问网站",
    "settings_get_help": "访问支持中心",
    "settings_version": "版本",
    "smart_list_inbox": "收件箱",
    "label_add_to_wunderlist": "添加到奇妙清单",
    "public_list_label_logged_in_as": "登录帐户",
    "label_add_instantly_to": "实时添加到...",
    "label_add_instantly_to_inbox": "实时添加到收件箱",
    "label_add_link_url_to": "添加链接URL到...",
    "label_add_link_url_to_inbox": "添加链接URL到收件箱",
    "label_add_audio_url_to": "添加音频URL到...",
    "label_add_audio_url_to_inbox": "添加音频URL到收件箱",
    "label_add_image_url_to": "添加图像URL到...",
    "label_add_image_url_to_inbox": "添加图像URL到收件箱",
    "label_add_video_url_to": "添加视频URL到...",
    "label_add_video_url_to_inbox": "添加视频URL到收件箱",
  },
  "zh-TW": {
    "button_download": "下載",
    "button_sign_in": "登入",
    "button_log_out": "登出",
    "button_download": "下載",
    "label_due_date": "到期日",
    "label_new_list": "新增清單",
    "label_reminder": "提醒",
    "rate_label": "喜歡奇妙清單？",
    "rate_app_button_yes": "現在就幫奇妙清單打分數",
    "placeholder_list_name": "清單名稱",
    "placeholder_add_note": "添加註釋...",
    "placeholder_add_task_mobile": "新增任務...",
    "placeholder_new_list": "新增清單",
    "placeholder_remind_me": "提醒我",
    "settings_visit_website": "訪問網站",
    "settings_get_help": "瀏覽技術支援中心",
    "settings_version": "版本",
    "smart_list_inbox": "收件匣",
    "label_add_to_wunderlist": "新增到奇妙清單",
    "public_list_label_logged_in_as": "登入帳號",
    "label_add_instantly_to": "即時新增到...",
    "label_add_instantly_to_inbox": "即時新增到收件夾",
    "label_add_link_url_to": "新增連結URL到...",
    "label_add_link_url_to_inbox": "新增連結URL到收件夾",
    "label_add_audio_url_to": "新增語音URL到...",
    "label_add_audio_url_to_inbox": "新增語音URL到收件夾",
    "label_add_image_url_to": "新增圖像URL到...",
    "label_add_image_url_to_inbox": "新增圖像URL到收件夾",
    "label_add_video_url_to": "新增影片URL到...",
    "label_add_video_url_to_inbox": "新增影片URL到收件夾",
  }
};